{
 "title": "MLOps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(${A} / ${B}) * 100", "type": "math" }
   ]
  },
  {
   "title": "success 200 OK",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "success_200", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "((${A} + ${B} + ${C}) / ${D}) * 100",
     "type": "math"
    }
   ]
  }
 ]
}