name: Retrain on Data PR

on:
  pull_request:
    branches: [ main ]  # Trigger only when PR targets the `main` branch
    paths:
      - 'data/**'               # If any data file changes
      - 'src/preprocess.py'     # If preprocessing script changes
      - 'src/train.py'          # If training script changes

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Preprocessing
      run: python src/preprocess.py

    - name: Train Model
      run: python src/train.py

    - name: Upload trained model and scaler
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/best_model.pkl
          models/scaler.pkl
